/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/8.5.73
 * Generated at: 2021-12-07 07:06:33 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class index_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  static {
    _jspx_dependants = new java.util.HashMap<java.lang.String,java.lang.Long>(2);
    _jspx_dependants.put("/views/common/footer.jsp", Long.valueOf(1638330540000L));
    _jspx_dependants.put("/views/common/header1.jsp", Long.valueOf(1638860451079L));
  }

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    final java.lang.String _jspx_method = request.getMethod();
    if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method) && !javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSP들은 오직 GET, POST 또는 HEAD 메소드만을 허용합니다. Jasper는 OPTIONS 메소드 또한 허용합니다.");
      return;
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<html>\r\n");
      out.write("<head>\r\n");
      out.write("<meta charset=\"UTF-8\">\r\n");
      out.write("<title>메인화면</title>\r\n");
      out.write("</head>\r\n");
      out.write("<body>\r\n");
      out.write("\r\n");
      out.write(" <!-- 상단에는 header1.jsp가 보이게 해줌 -->\r\n");
      out.write("\r\n");
      out.write("    \r\n");
      out.write("   \r\n");
      out.write("    \r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<html>\r\n");
      out.write("<head>\r\n");
      out.write("<meta charset=\"UTF-8\">\r\n");
      out.write("<title>고정헤더</title>\r\n");
      out.write("\r\n");
      out.write("<!-- Latest compiled and minified CSS -->\r\n");
      out.write("  <link rel=\"stylesheet\" href=\"https://maxcdn.bootstrapcdn.com/bootstrap/4.5.2/css/bootstrap.min.css\">\r\n");
      out.write("\r\n");
      out.write("  <!-- jQuery library -->\r\n");
      out.write("  <script src=\"https://ajax.googleapis.com/ajax/libs/jquery/3.5.1/jquery.min.js\"></script>\r\n");
      out.write("\r\n");
      out.write("  <!-- Popper JS -->\r\n");
      out.write("  <script src=\"https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.16.0/umd/popper.min.js\"></script>\r\n");
      out.write("\r\n");
      out.write("  <!-- Latest compiled JavaScript -->\r\n");
      out.write("  <script src=\"https://maxcdn.bootstrapcdn.com/bootstrap/4.5.2/js/bootstrap.min.js\"></script>\r\n");
      out.write("\r\n");
      out.write("<style>\r\n");
      out.write("    #wrap {\r\n");
      out.write("        width: 1000px;\r\n");
      out.write("        height: 300px;\r\n");
      out.write("        margin: auto;\r\n");
      out.write("    }\r\n");
      out.write("    div, form{\r\n");
      out.write("        /*border: 1px solid black;*/\r\n");
      out.write("        box-sizing: border-box;\r\n");
      out.write("    }\r\n");
      out.write("    #miniMenu { height:3%;} \r\n");
      out.write("    #miniMenu>button {\r\n");
      out.write("        float: right;\r\n");
      out.write("        border-radius: 5px;\r\n");
      out.write("    }\r\n");
      out.write("    #header {height: 15%;}\r\n");
      out.write("    #header>div {\r\n");
      out.write("        float: left;\r\n");
      out.write("    }\r\n");
      out.write("    #search {width: 80%; height: 100%; position: relative;}\r\n");
      out.write("    #search_form {\r\n");
      out.write("        width: 80%;\r\n");
      out.write("        height: 20%;\r\n");
      out.write("        margin: auto;\r\n");
      out.write("        position: absolute;\r\n");
      out.write("        right: 0px;\r\n");
      out.write("        left: 0px;\r\n");
      out.write("        top: 0px;\r\n");
      out.write("        bottom: 0px;\r\n");
      out.write("    }\r\n");
      out.write("    #search_form>div{\r\n");
      out.write("        height: 100%;\r\n");
      out.write("        float: left;\r\n");
      out.write("    }\r\n");
      out.write("    #search_form input {\r\n");
      out.write("        box-sizing: border-box;\r\n");
      out.write("        width: 100%;\r\n");
      out.write("        height: 100%;\r\n");
      out.write("    }\r\n");
      out.write("    #search_text { width: 90%; }\r\n");
      out.write("    #search_btn { width: 10%; }\r\n");
      out.write("\r\n");
      out.write("    #img {width: 20%; height: 100%;}\r\n");
      out.write("    #nav { height: 5%;}\r\n");
      out.write("    #cat {\r\n");
      out.write("        list-style-type: none;\r\n");
      out.write("        margin: 0px;\r\n");
      out.write("        padding: 0px;\r\n");
      out.write("        height: 100%;\r\n");
      out.write("    }\r\n");
      out.write("    #cat>li {\r\n");
      out.write("        float: left;\r\n");
      out.write("        width: 20%;\r\n");
      out.write("        height: 100%;\r\n");
      out.write("        text-align: center;\r\n");
      out.write("    }\r\n");
      out.write("    #cat a {\r\n");
      out.write("        text-decoration: none;\r\n");
      out.write("        color: black;\r\n");
      out.write("        font-size: 13px;\r\n");
      out.write("        font-weight: 900;\r\n");
      out.write("        width: 100%;\r\n");
      out.write("        height: 100%;\r\n");
      out.write("        display: block;\r\n");
      out.write("        line-height: 35px;\r\n");
      out.write("    }\r\n");
      out.write("    #cat li:hover {\r\n");
      out.write("        background-color: rgb(67, 155, 68);\r\n");
      out.write("    }\r\n");
      out.write("    #cat a:hover {\r\n");
      out.write("        color: white;\r\n");
      out.write("    }\r\n");
      out.write("   \r\n");
      out.write("</style>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("</head>\r\n");
      out.write("<body>\r\n");
      out.write("    <div id=\"wrap\">\r\n");
      out.write("        <div id=\"miniMenu\">\r\n");
      out.write("            <button><a href=\"/javajo/list.fb?currentPage=1\">게시판</a></button>\r\n");
      out.write("            <button><a href=\"/javajo/list.ad?currentPage=1\">관리자</a></button>\r\n");
      out.write("            <button>마이페이지</button>\r\n");
      out.write("            <button>고객센터</button>\r\n");
      out.write("        </div>\r\n");
      out.write("        <div id=\"header\">\r\n");
      out.write("            <div id=\"img\"><a href=\"\"><img src=\"resources\\mainImage.png\" style=\"width:100%; height: 100%;\"></a></div>\r\n");
      out.write("            <div id=\"search\">\r\n");
      out.write("                <form id=\"search_form\" action=\"search.do\" method=\"post\">\r\n");
      out.write("                    <div id=\"search_text\">\r\n");
      out.write("                        <input type=\"text\" placeholder=\"내용을 입력해주세요\">\r\n");
      out.write("                    </div>\r\n");
      out.write("                    <div id=\"search_btn\">\r\n");
      out.write("                        <input type=\"submit\" value=\"검색\">\r\n");
      out.write("                    </div>\r\n");
      out.write("                </form>\r\n");
      out.write("            </div>\r\n");
      out.write("        </div>\r\n");
      out.write("\r\n");
      out.write("        <div id=\"nav\">\r\n");
      out.write("            <ul id=\"cat\">\r\n");
      out.write("                <li><a>국내도서</a></li>\r\n");
      out.write("                <li><a>해외도서</a></li>\r\n");
      out.write("                <li><a>초/중/고 참고서</a></li>\r\n");
      out.write("                <li><a>대학교재</a></li>\r\n");
      out.write("                <li><a>수험서/자격증</a></li>\r\n");
      out.write("            </ul>\r\n");
      out.write("        </div>\r\n");
      out.write("       \r\n");
      out.write("            \r\n");
      out.write("    </div>\r\n");
      out.write("    \r\n");
      out.write("\r\n");
      out.write("</body>\r\n");
      out.write("</html>");
      out.write('\r');
      out.write('\n');
      out.write("\r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<html>\r\n");
      out.write("<head>\r\n");
      out.write("<meta charset=\"UTF-8\">\r\n");
      out.write("<title>하단고정</title>\r\n");
      out.write("<style>\r\n");
      out.write("    #wrap {\r\n");
      out.write("        width: 1000px;\r\n");
      out.write("        height: 1000px;\r\n");
      out.write("        margin: auto;\r\n");
      out.write("    }\r\n");
      out.write("    div, form{\r\n");
      out.write("        /*border: 1px solid black;*/\r\n");
      out.write("        box-sizing: border-box;\r\n");
      out.write("    }\r\n");
      out.write("   \r\n");
      out.write("    #footer {height: 22%;}\r\n");
      out.write("    #footer1 {\r\n");
      out.write("        height: 20%;\r\n");
      out.write("    }\r\n");
      out.write("    #footer2 {\r\n");
      out.write("        height: 75%;\r\n");
      out.write("    }\r\n");
      out.write("    #miniFoot>li {\r\n");
      out.write("        list-style-type: none;\r\n");
      out.write("        text-decoration: none;\r\n");
      out.write("        float: left;\r\n");
      out.write("        width: 20%;\r\n");
      out.write("        height: 100%;\r\n");
      out.write("        text-align: center;\r\n");
      out.write("    }\r\n");
      out.write("    #miniFoot>li a{\r\n");
      out.write("        color: gray;\r\n");
      out.write("    }\r\n");
      out.write("    #miniFoot>li a:hover {\r\n");
      out.write("        font-weight: 900;\r\n");
      out.write("        cursor: pointer;\r\n");
      out.write("    }\r\n");
      out.write("\r\n");
      out.write("</style>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("</head>\r\n");
      out.write("<body>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("    <div id=\"wrap\">\r\n");
      out.write("    <hr>\r\n");
      out.write("    <div id=\"footer\">\r\n");
      out.write("        <div id=\"footer1\" style=\"height: 20%;\">\r\n");
      out.write("            <ul id=\"miniFoot\">\r\n");
      out.write("                <li><a>FAQ</a></li>\r\n");
      out.write("                <li><a>회사소개</a></li>\r\n");
      out.write("                <li><a>채용</a></li>\r\n");
      out.write("                <li><a>이용약관</a></li>\r\n");
      out.write("                <li><a>개인정보처리방침</a></li>\r\n");
      out.write("            </ul>\r\n");
      out.write("        </div>\r\n");
      out.write("        <hr>\r\n");
      out.write("        <div id=\"footer2\" style=\"height: 75%;\">\r\n");
      out.write("            <p style=\"height: 70%; font-size: 13px; \">\r\n");
      out.write("                고객문의 cs@daangnservice.com 제휴문의 contact@daangn.com <br>\r\n");
      out.write("                지역광고 ad@daangn.com PR문의 pr@daangn.com <br>\r\n");
      out.write("                <br>\r\n");
      out.write("                서울특별시 구로구 디지털로30길 28, 609호 (오이서비스)\r\n");
      out.write("                사업자 등록번호 : 375-87-00088 직업정보제공사업 신고번호 : J1200020200016\r\n");
      out.write("                <br><br>\r\n");
      out.write("                <a><img src=\"resources\\facebook.svg\"></a>\r\n");
      out.write("                <a><img src=\"resources\\instar.svg\"></a>\r\n");
      out.write("                <a><img src=\"resources\\blog.svg\"></a>\r\n");
      out.write("            </p>\r\n");
      out.write("            <p style=\"color: gray; font-size: 12px;\">\r\n");
      out.write("                ©Cucumber Market Inc.\r\n");
      out.write("            </p>\r\n");
      out.write("        </div>\r\n");
      out.write("\r\n");
      out.write("</div>\r\n");
      out.write("\r\n");
      out.write("</div>\r\n");
      out.write("</body>\r\n");
      out.write("</html>");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("</body>\r\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
