/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/8.5.73
 * Generated at: 2021-12-02 05:48:52 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.views.F_005fboard;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;
import java.util.ArrayList;
import com.kh.f_board.model.vo.Board;
import com.kh.common.model.vo.PageInfo;

public final class f_005fboardListView_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  static {
    _jspx_dependants = new java.util.HashMap<java.lang.String,java.lang.Long>(1);
    _jspx_dependants.put("/views/F_board/../common/header1.jsp", Long.valueOf(1638423875275L));
  }

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = new java.util.HashSet<>();
    _jspx_imports_classes.add("com.kh.common.model.vo.PageInfo");
    _jspx_imports_classes.add("com.kh.f_board.model.vo.Board");
    _jspx_imports_classes.add("java.util.ArrayList");
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    final java.lang.String _jspx_method = request.getMethod();
    if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method) && !javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSP들은 오직 GET, POST 또는 HEAD 메소드만을 허용합니다. Jasper는 OPTIONS 메소드 또한 허용합니다.");
      return;
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("    \r\n");
      out.write("\r\n");

	ArrayList<Board> list = (ArrayList<Board>)request.getAttribute("list");
	PageInfo pi = (PageInfo)request.getAttribute("pi");
	
	// 페이징바 만들때 필요한 변수 미리 셋팅
	int currentPage = pi.getCurrentPage();
	int startPage = pi.getStartPage();
	int endPage = pi.getEndPage();
	int maxPage = pi.getMaxPage();

      out.write("\r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<html>\r\n");
      out.write("<head>\r\n");
      out.write("<meta charset=\"UTF-8\">\r\n");
      out.write("<title>Insert title here</title>\r\n");
      out.write("<style>\r\n");
      out.write("    .wrap {\r\n");
      out.write("      width: 1200px;\r\n");
      out.write("      margin: 0px auto;\r\n");
      out.write("      text-align: center;\r\n");
      out.write("    }\r\n");
      out.write("\r\n");
      out.write("    #board-side {\r\n");
      out.write("      float: left;\r\n");
      out.write("      width: 20%;\r\n");
      out.write("    }\r\n");
      out.write("\r\n");
      out.write("    #board-title {\r\n");
      out.write("      width: 200px;\r\n");
      out.write("      height: 200px;\r\n");
      out.write("      background: green;\r\n");
      out.write("      font-size: 25px;\r\n");
      out.write("      font-display: none;\r\n");
      out.write("      text-decoration: none;\r\n");
      out.write("      text-align: center;\r\n");
      out.write("      color: white;\r\n");
      out.write("      text-align: center;\r\n");
      out.write("      display: table-cell;\r\n");
      out.write("      vertical-align: middle;\r\n");
      out.write("    }\r\n");
      out.write("\r\n");
      out.write("    #board-center {\r\n");
      out.write("      float: left;\r\n");
      out.write("      padding: 30px;\r\n");
      out.write("      width: 80%;\r\n");
      out.write("    }\r\n");
      out.write("\r\n");
      out.write("    #board-center-body {\r\n");
      out.write("      width: 100%;\r\n");
      out.write("      text-align: center;\r\n");
      out.write("    }\r\n");
      out.write("\r\n");
      out.write("    .hr1 {\r\n");
      out.write("      border: 0;\r\n");
      out.write("      height: 2px;\r\n");
      out.write("      background: green;\r\n");
      out.write("    }\r\n");
      out.write("\r\n");
      out.write("    .table-side td {\r\n");
      out.write("      border: 1px solid lightgrey;\r\n");
      out.write("      width: 200px;\r\n");
      out.write("      height: 50px;\r\n");
      out.write("      text-indent: 10px;\r\n");
      out.write("      text-align: left;\r\n");
      out.write("    }\r\n");
      out.write("\r\n");
      out.write("    .table-side tr:hover {\r\n");
      out.write("      color: green;\r\n");
      out.write("    }\r\n");
      out.write("\r\n");
      out.write("    #pagination {\r\n");
      out.write("      display: inline-block;\r\n");
      out.write("    }\r\n");
      out.write("\r\n");
      out.write("    #btn-write {\r\n");
      out.write("      float: right;\r\n");
      out.write("      margin-right: 20px;\r\n");
      out.write("    }\r\n");
      out.write("\r\n");
      out.write("    #board-center-header {\r\n");
      out.write("      text-align: left;\r\n");
      out.write("    }\r\n");
      out.write("  </style>\r\n");
      out.write("</head>\r\n");
      out.write("\r\n");
      out.write("<body>\r\n");
      out.write("\r\n");
      out.write("	");
      out.write("\r\n");
      out.write("    ");

	String contextPath = request.getContextPath(); // 

	// 성공 / 경고 메시지 뽑기
	String alertMsg = (String)session.getAttribute("alertMsg");
	// 서비스 요청 전 : alertMsg = null
	// 서비스 요청 후 성공 시 : alertMsg = 메시지 문구

      out.write("\r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<html>\r\n");
      out.write("<head>\r\n");
      out.write("<meta charset=\"UTF-8\">\r\n");
      out.write("<title>고정헤더</title>\r\n");
      out.write("\r\n");
      out.write("<!-- Latest compiled and minified CSS -->\r\n");
      out.write("  <link rel=\"stylesheet\" href=\"https://maxcdn.bootstrapcdn.com/bootstrap/4.5.2/css/bootstrap.min.css\">\r\n");
      out.write("\r\n");
      out.write("  <!-- jQuery library -->\r\n");
      out.write("  <script src=\"https://ajax.googleapis.com/ajax/libs/jquery/3.5.1/jquery.min.js\"></script>\r\n");
      out.write("\r\n");
      out.write("  <!-- Popper JS -->\r\n");
      out.write("  <script src=\"https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.16.0/umd/popper.min.js\"></script>\r\n");
      out.write("\r\n");
      out.write("  <!-- Latest compiled JavaScript -->\r\n");
      out.write("  <script src=\"https://maxcdn.bootstrapcdn.com/bootstrap/4.5.2/js/bootstrap.min.js\"></script>\r\n");
      out.write("\r\n");
      out.write("<style>\r\n");
      out.write("    #wrap {\r\n");
      out.write("        width: 1000px;\r\n");
      out.write("        height: 1000px;\r\n");
      out.write("        margin: auto;\r\n");
      out.write("    }\r\n");
      out.write("    div, form{\r\n");
      out.write("        /*border: 1px solid black;*/\r\n");
      out.write("        box-sizing: border-box;\r\n");
      out.write("    }\r\n");
      out.write("    #miniMenu { height:3%;} \r\n");
      out.write("    #miniMenu>button {\r\n");
      out.write("        float: right;\r\n");
      out.write("        border-radius: 5px;\r\n");
      out.write("    }\r\n");
      out.write("    #header {height: 15%;}\r\n");
      out.write("    #header>div {\r\n");
      out.write("        float: left;\r\n");
      out.write("    }\r\n");
      out.write("    #search {width: 80%; height: 100%; position: relative;}\r\n");
      out.write("    #search_form {\r\n");
      out.write("        width: 80%;\r\n");
      out.write("        height: 20%;\r\n");
      out.write("        margin: auto;\r\n");
      out.write("        position: absolute;\r\n");
      out.write("        right: 0px;\r\n");
      out.write("        left: 0px;\r\n");
      out.write("        top: 0px;\r\n");
      out.write("        bottom: 0px;\r\n");
      out.write("    }\r\n");
      out.write("    #search_form>div{\r\n");
      out.write("        height: 100%;\r\n");
      out.write("        float: left;\r\n");
      out.write("    }\r\n");
      out.write("    #search_form input {\r\n");
      out.write("        box-sizing: border-box;\r\n");
      out.write("        width: 100%;\r\n");
      out.write("        height: 100%;\r\n");
      out.write("    }\r\n");
      out.write("    #search_text { width: 90%; }\r\n");
      out.write("    #search_btn { width: 10%; }\r\n");
      out.write("\r\n");
      out.write("    #img {width: 20%; height: 100%;}\r\n");
      out.write("    #nav { height: 5%;}\r\n");
      out.write("    #cat {\r\n");
      out.write("        list-style-type: none;\r\n");
      out.write("        margin: 0px;\r\n");
      out.write("        padding: 0px;\r\n");
      out.write("        height: 100%;\r\n");
      out.write("    }\r\n");
      out.write("    #cat>li {\r\n");
      out.write("        float: left;\r\n");
      out.write("        width: 20%;\r\n");
      out.write("        height: 100%;\r\n");
      out.write("        text-align: center;\r\n");
      out.write("    }\r\n");
      out.write("    #cat a {\r\n");
      out.write("        text-decoration: none;\r\n");
      out.write("        color: black;\r\n");
      out.write("        font-size: 13px;\r\n");
      out.write("        font-weight: 900;\r\n");
      out.write("        width: 100%;\r\n");
      out.write("        height: 100%;\r\n");
      out.write("        display: block;\r\n");
      out.write("        line-height: 35px;\r\n");
      out.write("    }\r\n");
      out.write("    #cat li:hover {\r\n");
      out.write("        background-color: rgb(67, 155, 68);\r\n");
      out.write("    }\r\n");
      out.write("    #cat a:hover {\r\n");
      out.write("        color: white;\r\n");
      out.write("    }\r\n");
      out.write("   \r\n");
      out.write("</style>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("</head>\r\n");
      out.write("<body>\r\n");
      out.write("\r\n");
      out.write("    <div id=\"wrap\">\r\n");
      out.write("        <div id=\"miniMenu\">\r\n");
      out.write("            <button><a href=\"/javajo/list.fb\">회원가입</a></button>\r\n");
      out.write("            <button>로그인</button>\r\n");
      out.write("            <button>마이페이지</button>\r\n");
      out.write("            <button>고객센터</button>\r\n");
      out.write("        </div>\r\n");
      out.write("        <div id=\"header\">\r\n");
      out.write("            <div id=\"img\"><a href=\"\"><img src=\"resources\\mainImage.png\" style=\"width:100%; height: 100%;\"></a></div>\r\n");
      out.write("            <div id=\"search\">\r\n");
      out.write("                <form id=\"search_form\" action=\"search.do\" method=\"post\">\r\n");
      out.write("                    <div id=\"search_text\">\r\n");
      out.write("                        <input type=\"text\" placeholder=\"내용을 입력해주세요\">\r\n");
      out.write("                    </div>\r\n");
      out.write("                    <div id=\"search_btn\">\r\n");
      out.write("                        <input type=\"submit\" value=\"검색\">\r\n");
      out.write("                    </div>\r\n");
      out.write("                </form>\r\n");
      out.write("            </div>\r\n");
      out.write("        </div>\r\n");
      out.write("\r\n");
      out.write("        <div id=\"nav\">\r\n");
      out.write("            <ul id=\"cat\">\r\n");
      out.write("                <li><a>국내도서</a></li>\r\n");
      out.write("                <li><a>해외도서</a></li>\r\n");
      out.write("                <li><a>초/중/고 참고서</a></li>\r\n");
      out.write("                <li><a>대학교재</a></li>\r\n");
      out.write("                <li><a>수험서/자격증</a></li>\r\n");
      out.write("            </ul>\r\n");
      out.write("        </div>\r\n");
      out.write("       \r\n");
      out.write("            \r\n");
      out.write("    </div>\r\n");
      out.write("    \r\n");
      out.write("\r\n");
      out.write("</body>\r\n");
      out.write("</html>");
      out.write("\r\n");
      out.write("\r\n");
      out.write("  <div class=\"wrap\">\r\n");
      out.write("\r\n");
      out.write("    <div id=\"board-body\">\r\n");
      out.write("      <div id=\"board-side\">\r\n");
      out.write("        <div id=\"board-title\" onclick=\"location.href=''\" style=\"cursor: pointer;\"><span>후기 게시판</span><br>COMUUNITY</div>\r\n");
      out.write("        <table class=\"table-side\">\r\n");
      out.write("          <tr>\r\n");
      out.write("            <td>공지사항</td>\r\n");
      out.write("          </tr>\r\n");
      out.write("          <tr>\r\n");
      out.write("            <td>1:1 문의</td>\r\n");
      out.write("          </tr>\r\n");
      out.write("          <tr>\r\n");
      out.write("            <td>FAQ문의</td>\r\n");
      out.write("          </tr>\r\n");
      out.write("        </table>\r\n");
      out.write("      </div>\r\n");
      out.write("\r\n");
      out.write("      <div id=\"board-center\">\r\n");
      out.write("        <div id=\"board-center-header\">\r\n");
      out.write("          <h2>후기 게시판</h2>\r\n");
      out.write("        </div>\r\n");
      out.write("        <hr class=\"hr1\">\r\n");
      out.write("        <div id=\"board-center-body\">\r\n");
      out.write("          <table class=\"table table-hover t-body\">\r\n");
      out.write("            <thead>\r\n");
      out.write("              <tr>\r\n");
      out.write("                <th scope=\"col\" style=\"width: 8%; text-align: center;\">번호</th>\r\n");
      out.write("                <th scope=\"col\" style=\"width: 47%; text-align: center;\">제목</th>\r\n");
      out.write("                <th scope=\"col\" style=\"width: 15%;\">글쓴이</th>\r\n");
      out.write("                <th scope=\"col\" style=\"width: 15%;\">조회</th>\r\n");
      out.write("                <th scope=\"col\" style=\"width: 15%;\">날짜</th>\r\n");
      out.write("              </tr>\r\n");
      out.write("            </thead>\r\n");
      out.write("            <tbody>\r\n");
      out.write("              ");
 if(list.isEmpty()) { 
      out.write(" <!-- 조회글 없음 -->\r\n");
      out.write("                	<tr>\r\n");
      out.write("                		<td colspan=\"5\">조회된 리스트가 없습니다.</td>\r\n");
      out.write("                	</tr>\r\n");
      out.write("                ");
 } else { 
      out.write("\r\n");
      out.write("                	<!-- 반복 : list 에 있는 값을 순차적으로 접근해서 뽑아오기 -->\r\n");
      out.write("                	");
 for(Board b : list) { 
      out.write("\r\n");
      out.write("                		<tr>\r\n");
      out.write("		                    <td>");
      out.print( b.getF_NO() );
      out.write("</td>\r\n");
      out.write("		                    <td>");
      out.print( b.getF_TITLE() );
      out.write("</td>\r\n");
      out.write("		                    <td>");
      out.print( b.getMEMBER_ID() );
      out.write("</td>\r\n");
      out.write("		                    <td>");
      out.print( b.getCOUNT() );
      out.write("</td>\r\n");
      out.write("		                    <td>");
      out.print( b.getCREATE_DATE() );
      out.write("</td>\r\n");
      out.write("                		</tr>\r\n");
      out.write("                	");
 } 
      out.write("\r\n");
      out.write("                ");
 } 
      out.write("\r\n");
      out.write("             </tbody>\r\n");
      out.write("          </table>\r\n");
      out.write("          \r\n");
      out.write("          <script>\r\n");
      out.write("        	$(function() {\r\n");
      out.write("        		$(\".t-body>tbody>tr\").click(function() {\r\n");
      out.write("        			var bno = $(this).children().eq(0).text();\r\n");
      out.write("        			\r\n");
      out.write("        			// /jsp/detail.bo?bno=X\r\n");
      out.write("        			location.href = \"/javajo/list.fb?bno=\" + bno;\r\n");
      out.write("        		});\r\n");
      out.write("        	});\r\n");
      out.write("        </script>\r\n");
      out.write("          \r\n");
      out.write("          \r\n");
      out.write("          <div id=\"btn-write\">\r\n");
      out.write("            <input type=\"button\" value=\"게시글 작성\">\r\n");
      out.write("          </div>\r\n");
      out.write("        </div>\r\n");
      out.write("\r\n");
      out.write("        <br>\r\n");
      out.write("        <br>\r\n");
      out.write("        \r\n");
      out.write("        \r\n");
      out.write("        <!-- 페이징바 -->\r\n");
      out.write("        <div align=\"center\" class=\"paging-area\">\r\n");
      out.write("        \r\n");
      out.write("        	<!-- 페이징바에서 < 를 담당 : 이전페이지로 이동 -->\r\n");
      out.write("        	");
 if(currentPage != 1) { 
      out.write("\r\n");
      out.write("        		<button onclick=\"location.href='/javajo/list.fb?currentPage=");
      out.print( currentPage - 1 );
      out.write("'\">&lt;</button>\r\n");
      out.write("        	");
 } 
      out.write("\r\n");
      out.write("        \r\n");
      out.write("        	<!-- 페이징바에서 숫자를 담당 -->\r\n");
      out.write("            ");
 for(int i = startPage; i <= endPage; i++) { 
      out.write("\r\n");
      out.write("            	<!-- 버튼이 눌렸을 때 해당 페이지로 이동하게끔 -->\r\n");
      out.write("            	");
 if(i != currentPage) { 
      out.write("\r\n");
      out.write("            		<button onclick=\"location.href='/javajo/list.fb?currentPage=");
      out.print( i );
      out.write('\'');
      out.write('"');
      out.write('>');
      out.print( i );
      out.write("</button>\r\n");
      out.write("            	");
 } else { 
      out.write("\r\n");
      out.write("            		<!-- 현재 내가 보고있는 페이지일 경우에는 클릭이 안되게끔 막고싶다. -->\r\n");
      out.write("            		<button disabled>");
      out.print( i );
      out.write("</button>\r\n");
      out.write("            	");
 } 
      out.write("\r\n");
      out.write("            ");
 } 
      out.write("\r\n");
      out.write("            \r\n");
      out.write("            <!-- 페이징바에서 > 를 담당 : 다음페이지로 이동 -->\r\n");
      out.write("            ");
 if(currentPage != maxPage) { 
      out.write("\r\n");
      out.write("            	<button onclick=\"location.href='/javajo/list.fb?currentPage=");
      out.print( currentPage + 1 );
      out.write("'\">&gt;</button>\r\n");
      out.write("            ");
 } 
      out.write("\r\n");
      out.write("            \r\n");
      out.write("        </div>\r\n");
      out.write("        \r\n");
      out.write("        \r\n");
      out.write("      </div>\r\n");
      out.write("    </div>\r\n");
      out.write("  </div>\r\n");
      out.write("\r\n");
      out.write("</body>\r\n");
      out.write("\r\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
