/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/8.5.73
 * Generated at: 2021-12-07 04:43:56 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.views.board;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class boardEnrollView_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  static {
    _jspx_dependants = new java.util.HashMap<java.lang.String,java.lang.Long>(1);
    _jspx_dependants.put("/views/board/../common/header1.jsp", Long.valueOf(1638453265444L));
  }

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    final java.lang.String _jspx_method = request.getMethod();
    if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method) && !javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSP들은 오직 GET, POST 또는 HEAD 메소드만을 허용합니다. Jasper는 OPTIONS 메소드 또한 허용합니다.");
      return;
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write('\r');
      out.write('\n');
      out.write('	');
String alertMsg = (String)session.getAttribute("alertMsg"); 
      out.write("\r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<html>\r\n");
      out.write("<head>\r\n");
      out.write("<meta charset=\"UTF-8\">\r\n");
      out.write("<meta http-equiv=\"X-UA-Compatible\" content=\"IE=edge\">\r\n");
      out.write("<meta name=\"viewport\" content=\"width=device-width, initial-scale=1.0\">\r\n");
      out.write("<title>자유게시판</title>\r\n");
      out.write("<!-- Latest compiled and minified CSS -->\r\n");
      out.write("<link rel=\"stylesheet\"\r\n");
      out.write("	href=\"https://maxcdn.bootstrapcdn.com/bootstrap/4.5.2/css/bootstrap.min.css\">\r\n");
      out.write("\r\n");
      out.write("<!-- jQuery library -->\r\n");
      out.write("<script\r\n");
      out.write("	src=\"https://ajax.googleapis.com/ajax/libs/jquery/3.5.1/jquery.min.js\"></script>\r\n");
      out.write("\r\n");
      out.write("<!-- Popper JS -->\r\n");
      out.write("<script\r\n");
      out.write("	src=\"https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.16.0/umd/popper.min.js\"></script>\r\n");
      out.write("\r\n");
      out.write("<!-- Latest compiled JavaScript -->\r\n");
      out.write("<script\r\n");
      out.write("	src=\"https://maxcdn.bootstrapcdn.com/bootstrap/4.5.2/js/bootstrap.min.js\"></script>\r\n");
      out.write("\r\n");
      out.write("<style>\r\n");
      out.write(".wrap {\r\n");
      out.write("	width: 1200px;\r\n");
      out.write("	margin: 0px auto;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("#header {\r\n");
      out.write("	width: 100%;\r\n");
      out.write("	height: 200px;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("#board-side {\r\n");
      out.write("	float: left;\r\n");
      out.write("	width: 20%;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("#board-title {\r\n");
      out.write("	width: 200px;\r\n");
      out.write("	height: 200px;\r\n");
      out.write("	background: green;\r\n");
      out.write("	font-size: 25px;\r\n");
      out.write("	font-display: none;\r\n");
      out.write("	text-decoration: none;\r\n");
      out.write("	text-align: center;\r\n");
      out.write("	color: white;\r\n");
      out.write("	text-align: center;\r\n");
      out.write("	display: table-cell;\r\n");
      out.write("	vertical-align: middle;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("#board-center {\r\n");
      out.write("	float: left;\r\n");
      out.write("	padding: 30px;\r\n");
      out.write("	width: 80%;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".hr1 {\r\n");
      out.write("	border: 0;\r\n");
      out.write("	height: 2px;\r\n");
      out.write("	background: green;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".table-side td {\r\n");
      out.write("	border: 1px solid lightgrey;\r\n");
      out.write("	width: 200px;\r\n");
      out.write("	height: 50px;\r\n");
      out.write("	text-indent: 10px;\r\n");
      out.write("	text-align: left;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".table-side tr:hover {\r\n");
      out.write("	color: green;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("#board-center-header>span {\r\n");
      out.write("	font-size: 25px;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("#title {\r\n");
      out.write("	width: 100%;\r\n");
      out.write("	resize: none;\r\n");
      out.write("	margin-bottom: 10px;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("#content {\r\n");
      out.write("	width: 100%;\r\n");
      out.write("	height: 500px;\r\n");
      out.write("	resize: none;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".input-file {\r\n");
      out.write("	margin: 10px 0px;\r\n");
      out.write("}\r\n");
      out.write("</style>\r\n");
      out.write("</head>\r\n");
      out.write("\r\n");
      out.write("<body>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("    \r\n");
      out.write("   \r\n");
      out.write("    \r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<html>\r\n");
      out.write("<head>\r\n");
      out.write("<meta charset=\"UTF-8\">\r\n");
      out.write("<title>고정헤더</title>\r\n");
      out.write("\r\n");
      out.write("<!-- Latest compiled and minified CSS -->\r\n");
      out.write("  <link rel=\"stylesheet\" href=\"https://maxcdn.bootstrapcdn.com/bootstrap/4.5.2/css/bootstrap.min.css\">\r\n");
      out.write("\r\n");
      out.write("  <!-- jQuery library -->\r\n");
      out.write("  <script src=\"https://ajax.googleapis.com/ajax/libs/jquery/3.5.1/jquery.min.js\"></script>\r\n");
      out.write("\r\n");
      out.write("  <!-- Popper JS -->\r\n");
      out.write("  <script src=\"https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.16.0/umd/popper.min.js\"></script>\r\n");
      out.write("\r\n");
      out.write("  <!-- Latest compiled JavaScript -->\r\n");
      out.write("  <script src=\"https://maxcdn.bootstrapcdn.com/bootstrap/4.5.2/js/bootstrap.min.js\"></script>\r\n");
      out.write("\r\n");
      out.write("<style>\r\n");
      out.write("    #wrap {\r\n");
      out.write("        width: 1000px;\r\n");
      out.write("        height: 300px;\r\n");
      out.write("        margin: auto;\r\n");
      out.write("    }\r\n");
      out.write("    div, form{\r\n");
      out.write("        /*border: 1px solid black;*/\r\n");
      out.write("        box-sizing: border-box;\r\n");
      out.write("    }\r\n");
      out.write("    #miniMenu { height:3%;} \r\n");
      out.write("    #miniMenu>button {\r\n");
      out.write("        float: right;\r\n");
      out.write("        border-radius: 5px;\r\n");
      out.write("    }\r\n");
      out.write("    #header {height: 15%;}\r\n");
      out.write("    #header>div {\r\n");
      out.write("        float: left;\r\n");
      out.write("    }\r\n");
      out.write("    #search {width: 80%; height: 100%; position: relative;}\r\n");
      out.write("    #search_form {\r\n");
      out.write("        width: 80%;\r\n");
      out.write("        height: 20%;\r\n");
      out.write("        margin: auto;\r\n");
      out.write("        position: absolute;\r\n");
      out.write("        right: 0px;\r\n");
      out.write("        left: 0px;\r\n");
      out.write("        top: 0px;\r\n");
      out.write("        bottom: 0px;\r\n");
      out.write("    }\r\n");
      out.write("    #search_form>div{\r\n");
      out.write("        height: 100%;\r\n");
      out.write("        float: left;\r\n");
      out.write("    }\r\n");
      out.write("    #search_form input {\r\n");
      out.write("        box-sizing: border-box;\r\n");
      out.write("        width: 100%;\r\n");
      out.write("        height: 100%;\r\n");
      out.write("    }\r\n");
      out.write("    #search_text { width: 90%; }\r\n");
      out.write("    #search_btn { width: 10%; }\r\n");
      out.write("\r\n");
      out.write("    #img {width: 20%; height: 100%;}\r\n");
      out.write("    #nav { height: 5%;}\r\n");
      out.write("    #cat {\r\n");
      out.write("        list-style-type: none;\r\n");
      out.write("        margin: 0px;\r\n");
      out.write("        padding: 0px;\r\n");
      out.write("        height: 100%;\r\n");
      out.write("    }\r\n");
      out.write("    #cat>li {\r\n");
      out.write("        float: left;\r\n");
      out.write("        width: 20%;\r\n");
      out.write("        height: 100%;\r\n");
      out.write("        text-align: center;\r\n");
      out.write("    }\r\n");
      out.write("    #cat a {\r\n");
      out.write("        text-decoration: none;\r\n");
      out.write("        color: black;\r\n");
      out.write("        font-size: 13px;\r\n");
      out.write("        font-weight: 900;\r\n");
      out.write("        width: 100%;\r\n");
      out.write("        height: 100%;\r\n");
      out.write("        display: block;\r\n");
      out.write("        line-height: 35px;\r\n");
      out.write("    }\r\n");
      out.write("    #cat li:hover {\r\n");
      out.write("        background-color: rgb(67, 155, 68);\r\n");
      out.write("    }\r\n");
      out.write("    #cat a:hover {\r\n");
      out.write("        color: white;\r\n");
      out.write("    }\r\n");
      out.write("   \r\n");
      out.write("</style>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("</head>\r\n");
      out.write("<body>\r\n");
      out.write("    <div id=\"wrap\">\r\n");
      out.write("        <div id=\"miniMenu\">\r\n");
      out.write("            <button><a href=\"/javajo/list.fb?currentPage=1\">회원가입</a></button>\r\n");
      out.write("            <button>로그인</button>\r\n");
      out.write("            <button>마이페이지</button>\r\n");
      out.write("            <button>고객센터</button>\r\n");
      out.write("        </div>\r\n");
      out.write("        <div id=\"header\">\r\n");
      out.write("            <div id=\"img\"><a href=\"\"><img src=\"resources\\mainImage.png\" style=\"width:100%; height: 100%;\"></a></div>\r\n");
      out.write("            <div id=\"search\">\r\n");
      out.write("                <form id=\"search_form\" action=\"search.do\" method=\"post\">\r\n");
      out.write("                    <div id=\"search_text\">\r\n");
      out.write("                        <input type=\"text\" placeholder=\"내용을 입력해주세요\">\r\n");
      out.write("                    </div>\r\n");
      out.write("                    <div id=\"search_btn\">\r\n");
      out.write("                        <input type=\"submit\" value=\"검색\">\r\n");
      out.write("                    </div>\r\n");
      out.write("                </form>\r\n");
      out.write("            </div>\r\n");
      out.write("        </div>\r\n");
      out.write("\r\n");
      out.write("        <div id=\"nav\">\r\n");
      out.write("            <ul id=\"cat\">\r\n");
      out.write("                <li><a>국내도서</a></li>\r\n");
      out.write("                <li><a>해외도서</a></li>\r\n");
      out.write("                <li><a>초/중/고 참고서</a></li>\r\n");
      out.write("                <li><a>대학교재</a></li>\r\n");
      out.write("                <li><a>수험서/자격증</a></li>\r\n");
      out.write("            </ul>\r\n");
      out.write("        </div>\r\n");
      out.write("       \r\n");
      out.write("            \r\n");
      out.write("    </div>\r\n");
      out.write("    \r\n");
      out.write("\r\n");
      out.write("</body>\r\n");
      out.write("</html>");
      out.write("\r\n");
      out.write("	<div class=\"wrap\">\r\n");
      out.write("\r\n");
      out.write("		<form action=\"/javajo/insert.fb\" id=\"enroll-form\" method=\"post\"\r\n");
      out.write("			enctype=\"multipart/form-data\">\r\n");
      out.write("\r\n");
      out.write("			<input type=\"hidden\" name=\"userNo\" value=\"1\">\r\n");
      out.write("\r\n");
      out.write("			<div id=\"board-body\">\r\n");
      out.write("				<div id=\"board-side\">\r\n");
      out.write("					<div id=\"board-title\" onclick=\"location.href=''\"\r\n");
      out.write("						style=\"cursor: pointer;\">\r\n");
      out.write("						<span>후기 게시판</span><br>COMUUNITY\r\n");
      out.write("					</div>\r\n");
      out.write("					<table class=\"table-side\">\r\n");
      out.write("						<tr>\r\n");
      out.write("							<td>공지사항</td>\r\n");
      out.write("						</tr>\r\n");
      out.write("						<tr>\r\n");
      out.write("							<td>1:1 문의</td>\r\n");
      out.write("						</tr>\r\n");
      out.write("						<tr>\r\n");
      out.write("							<td>FAQ문의</td>\r\n");
      out.write("						</tr>\r\n");
      out.write("					</table>\r\n");
      out.write("				</div>\r\n");
      out.write("				<div id=\"board-center\">\r\n");
      out.write("					<div id=\"board-center-header\">\r\n");
      out.write("						<span>게시글 작성하기</span>\r\n");
      out.write("						<button type=\"submit\" class=\"btn btn-success\"\r\n");
      out.write("							style=\"float: right;\" name=\"submit\">등록</button>\r\n");
      out.write("					</div>\r\n");
      out.write("					<hr class=\"hr1\">\r\n");
      out.write("					<div id=\"in_title\">\r\n");
      out.write("						<input type=\"text\" name=\"title\" id=\"title\" placeholder=\"제목\"\r\n");
      out.write("							required>\r\n");
      out.write("					</div>\r\n");
      out.write("\r\n");
      out.write("					<div id=\"in_content\">\r\n");
      out.write("						<textarea name=\"content\" id=\"content\" placeholder=\"내용\" required></textarea>\r\n");
      out.write("					</div>\r\n");
      out.write("\r\n");
      out.write("					<!-- 미리보기 영역-->\r\n");
      out.write("					<table>\r\n");
      out.write("						\r\n");
      out.write("						<tr>\r\n");
      out.write("							\r\n");
      out.write("							<td><img id=\"contentImg1\" width=\"223\" height=\"160\"></td>\r\n");
      out.write("							<td><img id=\"contentImg2\" width=\"223\" height=\"160\"></td>\r\n");
      out.write("							<td><img id=\"contentImg3\" width=\"223\" height=\"160\"></td>\r\n");
      out.write("							<td><img id=\"contentImg4\" width=\"223\" height=\"160\" ></td>\r\n");
      out.write("						</tr>\r\n");
      out.write("					</table>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("					<div id=\"file-area\">\r\n");
      out.write("						<input type=\"file\" id=\"file1\" name=\"file1\" onchange=\"loadImg(this,1)\"> \r\n");
      out.write("						<input type=\"file\" id=\"file2\" name=\"file2\" onchange=\"loadImg(this,2)\"> \r\n");
      out.write("						<input type=\"file\" id=\"file3\" name=\"file3\" onchange=\"loadImg(this,3)\">\r\n");
      out.write("						<input type=\"file\" id=\"file4\" name=\"file4\" onchange=\"loadImg(this,4)\">\r\n");
      out.write("					</div>\r\n");
      out.write("\r\n");
      out.write("					<script>\r\n");
      out.write("						$(function() {\r\n");
      out.write("\r\n");
      out.write("							$(\"#file-area\").hide();\r\n");
      out.write("\r\n");
      out.write("							$(\"#contentImg1\").click(function() {\r\n");
      out.write("								$(\"#file1\").click();\r\n");
      out.write("							});\r\n");
      out.write("\r\n");
      out.write("							$(\"#contentImg2\").click(function() {\r\n");
      out.write("								$(\"#file2\").click();\r\n");
      out.write("							})\r\n");
      out.write("							$(\"#contentImg3\").click(function() {\r\n");
      out.write("								$(\"#file3\").click();\r\n");
      out.write("							})\r\n");
      out.write("							$(\"#contentImg4\").click(function() {\r\n");
      out.write("								$(\"#file4\").click();\r\n");
      out.write("							})\r\n");
      out.write("						});\r\n");
      out.write("\r\n");
      out.write("						function loadImg(inputFile, num) {\r\n");
      out.write("\r\n");
      out.write("							// inputFile : 현재 변화가 생긴 <input type=\"file\"> 요소 객체\r\n");
      out.write("							// num : 몇번째 input 요소인지 확인 후 그 해당 영역에 미리보기 하기 위한 변수\r\n");
      out.write("\r\n");
      out.write("							console.log(inputFile.files.length);\r\n");
      out.write("							// inputFile.files.length : 파일 선택 시 1, 파일 선택 취소 시 0이 찍힘\r\n");
      out.write("							// => 파일의 존재 유무를 알 수 있다.\r\n");
      out.write("\r\n");
      out.write("							// files 속성 \" 업로드된 파일의 정보들을 배열 형식으로 여러개 묶어서 반환\"\r\n");
      out.write("\r\n");
      out.write("							if (inputFile.files.length == 1) { // 파일이 있는 경우\r\n");
      out.write("\r\n");
      out.write("								// 선택된 파일을 읽어들여서 그 영역에 맞는 곳에 미리보기\r\n");
      out.write("\r\n");
      out.write("								// 파일을 읽어들일 FileReader 객체 생성\r\n");
      out.write("								var reader = new FileReader();\r\n");
      out.write("\r\n");
      out.write("								// FileReader 객체로부터 파일을 읽어들이는 메소드를 호출\r\n");
      out.write("								// 어느 파일을 읽어들일건지 매개변수로 제시해야함 !!\r\n");
      out.write("								// 0번 인덱스에 담긴 파일 정보를 제시\r\n");
      out.write("								reader.readAsDataURL(inputFile.files[0]);\r\n");
      out.write("								// => 해당 파일을 읽어들이는 순간\r\n");
      out.write("								//    해당 그 파일만의 고유한 url 이 부여됨\r\n");
      out.write("								// => 해당 url 을 src 속성으로 부여할것 !\r\n");
      out.write("\r\n");
      out.write("								// 파일 읽기가 완료되었을 때 실행할 함수를 정의\r\n");
      out.write("								reader.onload = function(e) {\r\n");
      out.write("									// e의 target => e.target => 이벤트 당한 객체 (this)\r\n");
      out.write("\r\n");
      out.write("									// e 의 target.result 에 각 파일의 url 이 담긴다.\r\n");
      out.write("									// e.target.result == this.result\r\n");
      out.write("\r\n");
      out.write("									// 각 영역에 맞춰서 이미지 미리보기\r\n");
      out.write("									switch (num) {\r\n");
      out.write("									case 1:\r\n");
      out.write("										$(\"#contentImg1\").attr(\"src\", e.target.result);\r\n");
      out.write("										break;\r\n");
      out.write("									case 2:\r\n");
      out.write("										$(\"#contentImg2\").attr(\"src\", e.target.result);\r\n");
      out.write("										break;\r\n");
      out.write("									case 3:\r\n");
      out.write("										$(\"#contentImg3\").attr(\"src\", e.target.result);\r\n");
      out.write("										break;\r\n");
      out.write("									case 4:\r\n");
      out.write("										$(\"#contentImg4\").attr(\"src\", e.target.result);\r\n");
      out.write("										break;\r\n");
      out.write("									}\r\n");
      out.write("								};\r\n");
      out.write("\r\n");
      out.write("							} else { // 파일이 없는 경우 \r\n");
      out.write("								// 미리보기 사라지게 하기\r\n");
      out.write("								// src=null 을 담아서 사라지게 할 것\r\n");
      out.write("\r\n");
      out.write("								switch (num) {\r\n");
      out.write("								case 1:\r\n");
      out.write("									$(\"#contentImg1\").attr(\"src\", null);\r\n");
      out.write("									break;\r\n");
      out.write("								case 2:\r\n");
      out.write("									$(\"#contentImg2\").attr(\"src\", null);\r\n");
      out.write("									break;\r\n");
      out.write("								case 3:\r\n");
      out.write("									$(\"#contentImg3\").attr(\"src\", null);\r\n");
      out.write("									break;\r\n");
      out.write("								case 4:\r\n");
      out.write("									$(\"#contentImg4\").attr(\"src\", null);\r\n");
      out.write("									break;\r\n");
      out.write("								}\r\n");
      out.write("\r\n");
      out.write("							}\r\n");
      out.write("\r\n");
      out.write("						}\r\n");
      out.write("					</script>\r\n");
      out.write("\r\n");
      out.write("				</div>\r\n");
      out.write("			</div>\r\n");
      out.write("		</form>\r\n");
      out.write("	</div>\r\n");
      out.write("</body>\r\n");
      out.write("\r\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
